## JOB定义表
DROP TABLE IF EXISTS BH_JOB;
CREATE TABLE `BH_JOB` (
   `ID` int(11) NOT NULL AUTO_INCREMENT,
   `JOB_NAME` varchar(100) DEFAULT NULL,
   `JOB_GROUP` varchar(255) DEFAULT NULL,
   `JOB_INSTANCE_ID` varchar(20) DEFAULT NULL,
   `CRON` varchar(20) DEFAULT NULL,
   `DESCRIPTION` varchar(200) DEFAULT NULL,
   `STATUS` varchar(20) DEFAULT NULL,
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

## 测试任务表
DROP TABLE IF EXISTS CAT;
CREATE TABLE `CAT` (
   `ID` int(11) NOT NULL AUTO_INCREMENT,
   `CATNAME` varchar(30) DEFAULT NULL,
   `CATAGE` varchar(10) DEFAULT NULL,
   `CATADDRESS` varchar(255) DEFAULT NULL,
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;