## JOB定义表
DROP TABLE IF EXISTS BH_JOB;
CREATE TABLE `BH_JOB` (
   `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
   `JOB_NAME` varchar(100) DEFAULT NULL COMMENT '任务名称（bean ID）',
   `JOB_GROUP` varchar(255) DEFAULT NULL COMMENT '任务分组',
   `JOB_INSTANCE_ID` varchar(20) DEFAULT NULL COMMENT '任务实例ID（记录本次执行的实例，可用于续跑）',
   `CRON` varchar(20) DEFAULT NULL COMMENT '调度时间配置',
   `DESCRIPTION` varchar(200) DEFAULT NULL COMMENT '任务描述',
   `STATUS` varchar(20) DEFAULT NULL COMMENT '任务状态',
   `IS_MULTI_RUN` varchar(10) DEFAULT 'YES' COMMENT '当天任务是否可以多次执行',
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

## 测试任务表
DROP TABLE IF EXISTS CAT;
CREATE TABLE `CAT` (
   `ID` int(11) NOT NULL AUTO_INCREMENT,
   `CATNAME` varchar(30) DEFAULT NULL,
   `CATAGE` varchar(10) DEFAULT NULL,
   `CATADDRESS` varchar(255) DEFAULT NULL,
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;