##JOB测试数据
INSERT INTO `BATCH_JOB` (`JOB_NAME`,`JOB_GROUP`,`JOB_INSTANCE_ID`,`CRON`,`CRON_TEMPLATE`,`DESCRIPTION`,`STATUS`) VALUES ('testJob','A',NULL,'0 23 0 * * ?','0 23 0 * * ?','测试任务-远程分片','STARTED');
INSERT INTO `BATCH_JOB` (`JOB_NAME`,`JOB_GROUP`,`JOB_INSTANCE_ID`,`CRON`,`CRON_TEMPLATE`,`DESCRIPTION`,`STATUS`) VALUES ('spiltJob','B',NULL,'20 */1 * * * ?','20 */1 * * * ?','测试任务-拆分并行','STARTED');

INSERT INTO `mybatch`.`BATCH_JOB_CONFIG` (`CONF_CODE`, `CONF_VALUE`, `CONF_DESC`) VALUES ('TEST_ERROR_SWITCH', 'Y', '测试异常开关');
