##JOB测试数据
INSERT INTO `BH_JOB` (`JOB_NAME`,`JOB_GROUP`,`JOB_INSTANCE_ID`,`CRON`,`DESCRIPTION`,`STATUS`) VALUES ('testJob','A',NULL,'0 */1 * * * ?','测试任务-远程分片','STARTED');
INSERT INTO `BH_JOB` (`JOB_NAME`,`JOB_GROUP`,`JOB_INSTANCE_ID`,`CRON`,`DESCRIPTION`,`STATUS`) VALUES ('spiltJob','B',NULL,'20 */1 * * * ?','测试任务-拆分并行','STARTED');