server:
   port: 9090
quartz:
   enabled: true
spring:
   batch:
      job:
         enabled: false # 禁止应用启动时执行批量
         step:
            gridSize: 10000
            chunk: 1000
   messages:
      basename: i18n/Messages,i18n/Pages
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
      driver-class-name: com.mysql.jdbc.Driver # 配置MySQL的驱动程序类
      url: jdbc:mysql://192.168.171.10:3306/mybatch?useUnicode=true&characterEncoding=utf-8&useSSL=false # 数据库连接地址
      username: root # 数据库用户名
      password: Zcw@201901 # 数据库连接密码
      filters: stat,wall,log4j # 过滤器
      dbcp2: # 进行数据库连接池的配置
         min-idle: 5 # 数据库连接池的最小维持连接数    
         initial-size: 5 # 初始化提供的连接数
         max-total: 5 # 最大的连接数
         max-wait-millis: 200 # 等待连接获取的最大超时时间
   redis: 
      database: 0 # Redis数据库索引（默认为0）
      host: 192.168.171.10 # Redis服务器地址
      port: 6379 # Redis服务器连接端口
      password: 123456 # Redis服务器连接密码
      pool:
         max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
         max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-idle: 10 # 连接池中的最大空闲连接
         min-idle: 0 # 连接池中的最小空闲连接 
      timeout: 5000 # 连接超时时间（毫秒）
   activemq:
      broker-url: tcp://192.168.171.10:61616
      in-memory: false # true 表示使用内置的MQ，false则连接服务器
      pool:
         enable: true # true表示使用连接池；false时，每发送一条数据创建一个连接
         max-connections: 10 # 连接池最大连接数
         idle-timeout: 30000 # 空闲的连接过期时间，默认为30秒
         expiry-timeout: 0 # 强制的连接过期时间，与idleTimeout的区别在于：idleTimeout是在连接空闲一段时间失效，而expiryTimeout不管当前连接的情况，只要达到指定时间就失效。默认为0，never
#mybatis配置
mybatis-plus:
   mapper-locations: classpath:/mapper/*Mapper.xml
   #实体扫描，多个package用逗号或者分号分隔
   typeAliasesPackage: com.spring.clould.batch.entity
   typeEnumsPackage: com.spring.clould.batch.entity.enums
   global-config:
      db-config: # 数据库相关配置
         id-type: AUTO # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
         field-strategy: not_empty # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
         column-underline: true # 驼峰下划线转换
         capital-mode: true # 数据库大写下划线转换
         logic-delete-value: 0 # 逻辑删除配置
         logic-not-delete-value: 1 # 逻辑删除配置
         db-type: mysql # 数据库类型
      refresh: true # 刷新mapper 调试神器
   configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
#线程池配置
thread:
   pool:
      corePoolSize: 10
      maxPoolSize: 20
      queueCapacity: 100
      keepAliveSeconds: 30000